### ISSUE TITLE
The issue with color encoding for mutations by type

### ISSUE THREAD

**Issue by SashaNikitski** [pearcetm/jscomut#1]
Hi all,
When plotting, all data in genetic alterations sections are shown as black without possibility to change it
Thank you
Sincerely,
Sasha

**Comment by pearcetm** [comment]
Thanks for pointing this out. It appears that recent browser updates no longer allowed non-#-prefixed hex color strings, converting them to black instead. The issue should be fixed now.

**Comment by SashaNikitski** [comment]
Thank you for a prompt reply. It works fine now. Yes, the issue appeared after recent updates.
